name: Build images
on:
  push:
  workflow_dispatch:

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\nedge\nfairphone\nfp4\n\n\nphosh\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports

      - name: Choose any SM7125 device in pmbootstrap to build kernel
        run: |
          cp xiaomi-lavender.cfg ~/.config/pmbootstrap_v3.cfg

      - name: Create artifact directory
        run: |
          mkdir out

      - name: Build xiaomi-lavender
        run: |
          cp xiaomi-lavender.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          ls /tmp/postmarketOS-export/ -la
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-lavender.img

          # for case without "--split", the resulting file is xiaomi.img
          cp /tmp/postmarketOS-export/*lavender*.img out/ || true

          # for case with split, the result file is xiaomi-root.img
          cp /tmp/postmarketOS-export/*lavender-*.img out/ || true
          
          #sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
          #pmbootstrap export
          #cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-miatoll.img
          #xz -T0 -9e -v out/xiaomi-miatoll*.img
          echo -e "n\nn\ny\n" | pmbootstrap zap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-lavender
          path: out/*lavender*.img*
          retention-days: 7
